# Generated by Django 3.2.25 on 2026-04-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hospital_system_app', '0002_auto_20260404_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='smart_hospital_system_app.clinic'),
            preserve_default=False,
        ),
    ]
