# Generated by Django 3.2.25 on 2026-04-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hospital_system_app', '0004_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
