# Generated by Django 3.2.25 on 2026-04-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hospital_system_app', '0005_profile'),
        ('smart_hospital_system_app', '0006_auto_20260412_1826'),
    ]

    operations = [
    ]
